### PR TITLE
Web scraper

### PR DESCRIPTION
**Pull request by RobertMadx**

### CODE REVIEW

**Comment by RobertMadx** [comment]
It's getting 13000+ item prices at the moment and takes approx. 40 minutes. This is not optimised yet but it's working. It needs to be modularised but not familiar with Laravel commands yet. Also not capturing all Personal care items, but then again we do not need that. Although some pages do have sub-sub-categories, I do not think we need to go that deep...
Think this is a good start and need to start on using this info in some way.
The idea is to schedule run (possible with Laravel) this command weekly or event monthly...

**Comment by benjamesfleming** [comment]
Good work on this, It looks like this is the way to go. I have just spent some time refactoring and cleaning up. 

Just a few things:
 1. Manual cookie handling can be removed by setting `['cookies' => true]`. shown [here](http://docs.guzzlephp.org/en/stable/request-options.html?highlight=cookies)
 2. Laravel has some prebuilt output function shown [here](https://laravel.com/docs/5.8/artisan#writing-output). 

Have a look over the code, if you see any major problems that I missed we easily can revert back to a working version.

**Comment by RobertMadx** [comment]
Yeah, this looks good.

I will change database column names to match the standard and keep it consistent.

Currently, we can filter on the date and should show one each(one per day depending on how often you run it). We have an ingredients_id in the ingredient_price_history table which we can link to ingredients, only thing is when we add updates, it will add records per day and then we somehow need to lookup previous ingredients_id when inserting. 
This is ugly but can be done, although I do not prefer it. 

Alternatively, we can have for example a vendor_ingredient table which we then use to store vendorproductid matched to ingredient(then remove the ingredients_id from table ingredient_price_history). This will resolve a potential many to many relationship... your thoughts?

Option 1: Leave as is and lookup ingredients_id with insert.
Option 2: New table vendor_ingredient
Option 3: I was thinking, do we really want to know the history? Nice to have but think it will increase database size exponentially considering locations have their own pricing per product. How about we just store or update the latest result instead of keeping history....

**Comment by benjamesfleming** [comment]
Option 4: don't scrape the whole site. We could make it that only when a user adds a new ingredient we scrape all the vendors & branches for that one items (e.g. a search), then average all those numbers and save it. This means that we only save the average price. so having a history table is not going to take to much space. After that initial search we could schedule a job to run once a week that gets the latest average price.

**Tables:**
 - `ingredients`, this saves all the user provided details. (e.g. name, unit, ...)
 - `ingredient_price_history`, this saves the average price, linked back to the `ingredients` table by foreign key.

We could create another table to make subsequent scrapes faster by keeping the url from the vendor. removing the need for a search. That might look like:

 - `ingredient_vendors`, this holds many vendors urls for each ingredient, linked back to the `ingredients` table by foreign key.

Then when we update our price table we do a  search on the `ingredient_vendors` table to get the latest urls for the given ingredient, scrape them all and save the average. If one of the urls is now dead, we can fallback on a search.

Here is a pseudo code example of an update function.
```php
public function update(Ingredient $ingredient)
{
    $urls = IngredientVendor::where('ingredient_id', '=', $ingredient->id)->all();
    $prices = [];

    // loop through saved urls
    foreach ($urls as $url)
    {
        $crawler = $this->request($url);

        if ($crawler->failed) 
            continue;

        // add price to array
        array_push(
            $prices, $crawler->getPrice()
        );
    }

    // save the average price
    IngredientPriceHistory::create([
        'ingredient_id' => $ingredient->id,
        'price' => array_sum($prices) / count($prices)
    ]);
}
```
Another benefit of this approach is that we could implement a rolling update system, maybe every 10-15 minutes we update the price of one ingredient.

**Pull request closed without merging**
